#!/bin/bash

# This is a program that accepts an sd card and formate raspbian images on it 

chmod +x sd_card2.sh # Saves the shell script
df -h # Views all devices including partitions on this very computer

# All commands that start with echo are to print texts(Texts in double )
echo "Please check for the name of your sd card beside /dev/ with its corresponding disk size."
echo "E.g. for /dev/sda, 'sda' is the disk name."
echo "Warning! Please confirm the name correctly to avoid BUM!!!"

sleep 1 # Slight pause

echo "Type the SD card name : "
read sd_card_name # Reads user input and save it to the variable sd_card_name
echo "You typed" $sd_card_name # Prints user input

#umount /dev/$sd_card_name # Unmounts sd card(umount might be unmount in SUSE)
#echo "Unmounting...."
#sleep 1.5 # Slight pause
#echo "SD Card has been unmounted"

dd bs=4M if=/dev/zero of=/dev/$sd_card_name # empty the sd_card by zero-ing out 
echo $sd_card_name "is done formatting!"
sleep 1 #slight pause

dd bs=4M if=/dev/image_path of=/dev/$sd_card_name # copy the images into the sd_card2
echo "raspbian images is done coping into" $sd_card_name

